# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [ ]:
%run initialise.py

#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [2]:
np.__version__

'1.20.1'

#### 3. Create a null vector of size 10 (★☆☆)

In [3]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. How to find the memory size of any array (★☆☆)

In [4]:
a=np.zeros(10) # create an array and save it in a variable 'a' (to be able to call the array later)
print("array size is:",a.size) # 'size' gives you number of elements in the array
print("array itemsize is:",a.itemsize,'bytes') # 'itemsize' gives you memory size of ONE array element in bytes
print("array memory size is:",a.size * a.itemsize,'bytes') # to get 'memory size' of the array you need to multiply 'array size' with 'array itemsize'

array size is: 10
array itemsize is: 8 bytes
array memory size is: 80 bytes


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [5]:
# by calling .info(np.ndarray.dtype)

np.info(np.add) 

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [6]:
np.array([0,0,0,0,1,0,0,0,0,0])

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [7]:
# using '.arange'(START,END,STEP)

np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [8]:
# Use numpy.flip(array, axis=None)
# Flip an array vertically (axis=0)
# Flip an array horizontally (axis=1)

a = np.array([1,2,3,4,5,6]) # creating an array 'a'
print(a)

np.flip(a,0) # reverse/flip the array 'a' (vertically) / axis=0

[1 2 3 4 5 6]


array([6, 5, 4, 3, 2, 1])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [15]:
a = np.arange(0,9).reshape(3,3)
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [16]:
np.nonzero([1,2,0,0,4,0])

(array([0, 1, 4], dtype=int64),)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [20]:
# 'identity' means main diogonal is same

np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [25]:
np.random.random((3,3))

array([[0.98836161, 0.90388522, 0.04673168],
       [0.0037573 , 0.59996971, 0.50872141],
       [0.58887704, 0.80755991, 0.97199265]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [32]:
a = np.random.random((10,10))
print(a)
print('minimum is: ',a.min())
print('maximum is: ',a.max())

[[0.26676824 0.48118105 0.0297063  0.93247084 0.79775348 0.33211736
  0.46318709 0.07838772 0.13282713 0.42295327]
 [0.40570006 0.59879908 0.41072648 0.12724173 0.07188153 0.98802109
  0.39110688 0.11695803 0.06387908 0.54555298]
 [0.52847783 0.95560337 0.14477219 0.33581642 0.34822471 0.55527588
  0.81039429 0.73468434 0.46302816 0.35093229]
 [0.64120023 0.40651739 0.95015668 0.4992088  0.32897361 0.13248223
  0.31993183 0.85035156 0.38875101 0.929695  ]
 [0.59198012 0.42178034 0.94746672 0.4232264  0.85938799 0.28842512
  0.89447205 0.74651935 0.50148306 0.60546836]
 [0.05337116 0.08670988 0.10682572 0.9548305  0.45956994 0.62358463
  0.93244496 0.07504594 0.17254744 0.41390179]
 [0.84534346 0.57007151 0.44579122 0.96850055 0.025378   0.15633807
  0.22804832 0.45127117 0.70864233 0.49499575]
 [0.1718591  0.13338491 0.64662618 0.37079689 0.92220148 0.29215531
  0.47942635 0.66618164 0.48460755 0.28814018]
 [0.94341119 0.4600972  0.62293224 0.1672727  0.6443906  0.54057453
  0.91162293

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [49]:
a = np.random.random(30)
print(a)
print('\n') # this is just a line break / empty line
print("mean of the array is: ",np.mean(a))

[0.74920096 0.97313303 0.71144481 0.87135597 0.50219479 0.9466857
 0.30570812 0.00144379 0.17501564 0.06746586 0.96535628 0.90813338
 0.10039062 0.9492532  0.62681902 0.78518925 0.0334286  0.5458307
 0.99553375 0.89245425 0.46019449 0.59979773 0.54036032 0.41939957
 0.4628385  0.74202825 0.87962477 0.53263187 0.00892716 0.09157716]


mean of array is:  0.5614472502058756


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [54]:
# 1st create an 5x5 array with 1's

x = np.ones((5,5)) 
print("Original array:")
print(x)

print('\n') # this is just a line break / empty line

print("1 on the border and 0 inside in the array")
x[1:-1,1:-1] = 0
print(x)

Original array:
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


1 on the border and 0 inside in the array
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [55]:
# 1st create an 3x3 array with 1's

x = np.ones((3,3))
print("Original array:")
print(x)

print('\n') # this is just a line break / empty line

# add 0's around the created array with '.pad(array, pad_width, mode='constant', **kwargs))'
# pad_width: = Number of values padded to the edges of each axis. 
# mode: str or function, optional / e.g. ‘constant’ (Pads with a constant value.)
# constant_values: Used in ‘constant’. The values to set the padded values for each axis.

print("0 on the border and 1 inside in the array")
x = np.pad(x, pad_width=1, mode='constant', constant_values=0)
print(x)

Original array:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
0 on the border and 1 inside in the array
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [62]:
# hint: NaN = not a number, inf = infinity

a = 0 * np.nan
print('0 * np.nan =',a)

b = np.nan == np.nan
print('np.nan == np.nan =',b)

c = np.inf > np.nan
print('np.inf > np.nan =',c)

d = np.nan - np.nan
print('np.nan - np.nan =',d)

e = np.nan in set([np.nan])
print('np.nan in set([np.nan]) =',e)

f = 0.3 == 3 * 0.1
print('0.3 == 3 * 0.1 =',f)


0 * np.nan = nan
np.nan == np.nan = False
np.inf > np.nan = False
np.nan - np.nan = nan
np.nan in set([np.nan]) = True
0.3 == 3 * 0.1 = False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [69]:
# numpy.diag(v, k=0)
# Extract a diagonal or construct a diagonal array.

# Parameters
# v = array_like
# If v is a 2-D array, return a copy of its k-th diagonal. If v is a 1-D array, return a 2-D array with v on the k-th diagonal.

# k = int, optional
# Diagonal in question. The default is 0. Use k>0 for diagonals above the main diagonal, and k<0 for diagonals below the main diagonal.

x = np.diag([1, 2, 3, 4, 5])
print(x)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [77]:
# You can use the STEP of START:STOP:STEP for slicing method to update a matrix horizontally and vertically:
# Here x[1::2,::2] picks every other element starting from the first element on the row and for every second row of the matrix.

print("Checkerboard pattern:")
x = np.zeros((8,8),dtype=int)   # create an 8x8 zero-array with integers
x[1::2,::2] = 1                 # for [odd rows(1::2),even columns(::2)] print 1
x[::2,1::2] = 1                 # for [even rows(::2), odd columns(1::2)] print 1
print(x)

Checkerboard pattern:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [82]:
# numpy.unravel_index(indices, shape, order='C')
# Converts a flat index or array of flat indices into a tuple of coordinate arrays.

print (np.unravel_index(100, (6,7,8)))

(1, 5, 4)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [96]:
# numpy.tile(A, reps)
# Construct an array by repeating 'A' the number of times given by 'reps'.
# A = The input array
# reps = The number of repetitions of 'A' along each axis.

array = np.array([[0,1], [1,0]])       # create a 2x2 matrix with checkboard pattern
print('start matrix:', '\n', array)

print('\n')

print('start matrix extended to 8x8:')
Z = np.tile(array,(4,4))               # use .tile to repeat pattern 4-times along each axis
print(Z)

start matrix: 
 [[0 1]
 [1 0]]


start matrix extended to 8x8:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [122]:
x = np.random.random((5,5))     # create a random 5x5 matrix
xmax, xmin = x.max(), x.min()   # define min & max of the matrix
x= (x-xmin)/(xmax-xmin)         
print (x)

[[0.60286519 0.7836445  0.33358307 0.86307388 0.56593895]
 [0.71019771 1.         0.22865864 0.0452735  0.57761071]
 [0.50042359 0.69458427 0.07444604 0.2830349  0.78467907]
 [0.29087327 0.93169722 0.87926696 0.32460438 0.97358182]
 [0.14202576 0.91994893 0.73466859 0.         0.04750543]]


In [113]:
#hint: (x -mean)/std

x = np.random.random((5,5))     # create a random 5x5 matrix
xmean = x.mean()                # find mean of matrix
xstd = x.std()                  # find std of the matrix
x= (x-xmean)/xstd               # subtract mean from matrix and divide it by std
print(x)

[[ 0.11366661 -0.96186822  1.39308594  1.5504363  -0.8764563 ]
 [-0.01537226 -0.04261449 -1.32977152  1.72047609  0.08243046]
 [ 0.61989841  1.80544408 -0.9658517   0.1481062  -1.60962572]
 [-0.34000248  1.84240894  0.27481697 -0.51616052 -0.538105  ]
 [ 0.0215677  -0.34926105 -1.47188192 -0.74550625  0.19013976]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [117]:
color = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])

<ipython-input-117-b9f1a6f5df9c>:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  color = np.dtype([("r", np.ubyte, 1),


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [121]:
Z = np.dot(np.ones((5,3)), np.ones((3,2)))
print(Z)

print('\n')

# Alternative solution, in Python 3.5 and above
Z = np.ones((5,3)) @ np.ones((3,2))
print(Z)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

#### 29. How to round away from zero a float array ? (★☆☆)

#### 30. How to find common values between two arrays? (★☆☆)

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

#### 40. Create a random vector of size 10 and sort it (★★☆)

#### 41. How to sum a small array faster than np.sum? (★★☆)

#### 42. Consider two random array A and B, check if they are equal (★★☆)

#### 43. Make an array immutable (read-only) (★★☆)

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

#### 49. How to print all the values of an array? (★★☆)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)